language: node_js
node_js:
  - "0.10"

before_install:
  - sudo apt-get update
  - sudo apt-get install make g++
  - wget https://launchpad.net/libmemcached/1.0/1.0.18/+download/libmemcached-1.0.18.tar.gz
  - ls
  - tar -xzf libmemcached*.tar.gz
  - cd libmemcached-1.0.18 && ./configure && make && sudo make install

notifications:
  email:
    recipients:
      - tomallevi@gmail.com
