language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"

before_install:
  - sudo apt-get update
  - sudo apt-get install libmemcached-dev

notifications:
  email:
    recipients:
      - tomallevi@gmail.com
