language: node_js

sudo: required
services:
  - docker

install:
  - docker build -t node/memcached-native .

script:
  - docker run --name my-memcache -d memcached
  - docker run --link my-memcache:memcache -it node/memcached-native npm test

notifications:
  email:
    recipients:
      - tomallevi@gmail.com
