language: node_js

sudo: required
services:
  - docker

before_install:
  - docker build -t node/memcached-native .
install:
  - echo "PASS..."
script:
  - docker run -it node/memcached-native npm run docker-build

notifications:
  email:
    recipients:
      - tomallevi@gmail.com
