language: node_js

sudo: required
services:
  - docker

install:
  - docker build -t node/memcached-native .

script:
  - docker run -it node/memcached-native memcached -h
  - docker run -it node/memcached-native npm run docker-build

notifications:
  email:
    recipients:
      - tomallevi@gmail.com
