language: node_js

sudo: required
services:
  - docker

install:
  - docker -v
  - docker build -t node/memcached-native .

script:
  - docker run --name my-memcache -d memcached
  - docker run --link my-memcache:memcache -v $(pwd):/repos -it node/memcached-native npm run build-travis

notifications:
  email:
    recipients:
      - tomallevi@gmail.com
